name: material_dev_tools

packages:
  - .
  - example

command:
  bootstrap:
    environments:
      sdk: ">=3.7.2 <4.0.0"
      flutter: ">=3.29.0"

  dependencies:
    flutter:
      sdk: flutter
    devtools_extensions: ^0.3.1
    devtools_app_shared: ^0.3.1
    vm_service: ^15.0.0

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^5.0.0
    melos: ^6.3.2

scripts:
  build_and_copy:
    run: dart run devtools_extensions build_and_copy --source=. --dest=extension/devtools
    packageFilters:
      scope: material_dev_tools
    description: Builds the web app and copies it into the proper folder.

  pub_publish_dry_run:
    run: flutter pub publish --dry-run
    packageFilters:
      scope: material_dev_tools
    description: The publish command in dry-run mode to see if everything passes analysis.

  use_simulated_environment:
    run: flutter run -d chrome --dart-define=use_simulated_environment=true
    packageFilters:
      scope: material_dev_tools
    description: Use the Simulated DevTools Environment (recommended for development).

  validate:
    run: dart run devtools_extensions validate --package=.
    packageFilters:
      scope: material_dev_tools
    description: Ensures that the extension is setup properly for loading in dev tools.
