name: material_dev_tools
description: Enhances the development workflow by offering real-time previews of Material components
version: 0.0.1
repository: https://github.com/josealba/material_dev_tools

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  devtools_extensions: ^0.3.1
  devtools_app_shared: ^0.3.1
  vm_service: ^14.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  melos: ^6.3.2

flutter:
  uses-material-design: true
