name: material_dev_tools
description: Enhances the development workflow by offering real-time previews of Material components
version: 0.0.6
repository: https://github.com/josealba/material_dev_tools

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.3.1
  devtools_app_shared: ^0.3.1
  flutter_localization: ^0.3.2
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  intl: ^0.19.0
  vm_service: ^14.3.1
  widgetbook: ^3.11.0
  widgetbook_annotation: ^3.3.0

dev_dependencies:
  build_runner: 2.4.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  melos: ^6.3.2
  pigeon: ^25.2.0 # https://github.com/flutter/flutter/issues/147909
  widgetbook_generator: 3.10.0

flutter:
  uses-material-design: true
